function [Mcx]=AmpMomSlenderColumns(b,h,fc,Pu,Wu,...
               m1b,m1s,m2b,m2s,delta,lelem,inertiax,Vu)

%------------------------------------------------------------------------
% Syntax:
% [Mcx]=AmpMomSlenderColumns(b,h,fc,Pu,Wu,...
%       m1b,m1s,m2b,m2s,delta,lelem,inertiax,Vu)
%-------------------------------------------------------------------------
% SYSTEM OF UNITS: SI - (Kg,cm)
%------------------------------------------------------------------------
% PURPOSE: To compute the amplified moments for a column considering the
%          slenderness effects.
% 
% OUTPUT: Mcx:      amplified moment in the X-direction (Ton-m)
%
% INPUT:  Pu:       is the axial load over the column's cross-section
%
%         Wu:       Wu is the sum of axial loads in the columns of the 
%                   i-floor (in which the column of analysis is placed)
%                   from the n floor (Kg)
%
%         fc:       is the f'c used (Kg/cm2) 
%
%         b,h:      are the column cross-section dimensions (cm)
%
%         m2b:      is the greater moment generated by the forces that 
%                   caused depreciable displacement on the structure: 
%                   (Ton-m)
%           
%         m2s:      is the greater moment generated by the forces that 
%                   caused the greater displacement on the structure: 
%                   (Ton-m)
%
%         m1b:      is the smaller moment generated by the forces that
%                   caused depreciable displacement on the structure:
%                   (Ton-m)
%
%         m1s:      is the smaller moment generated by the forces that 
%                   caused the greater displacement on the structure: 
%                   (Ton-m)
%
%         delta:    lateral displacement at the top of the column (cm)
%
%         height:   effective length of the column element (cm)

%         inertiax: inertia momentum for the axis direction in question of
%                   the cross-section ($cm^4$)
%
%         Vu:       shear base force (Kg)
%
%------------------------------------------------------------------------
% LAST MODIFIED: L.F.Veduzco    2022-02-05
%                Faculty of Engineering
%                Autonomous University of Queretaro
%------------------------------------------------------------------------

%%% Amplified moment in the direction in question
emin=0.02; %(m) equal to 2 cm
momMin=Pu*0.001*emin; % Ton,m

    Q=4; % High ductility
lamda=Wu*delta*Q/(lelem*Vu);

Fas=1/(1-lamda);
if Fas<1
    Fas=1;
end

m2=m2b(1)+Fas*m2s(1);
m1=m1b(1)+Fas*m1s(1);
if m2<momMin
    m2=momMin;
end
Mcx=m2;
r=sqrt(h^2/12);
if lelem/r>=35/(sqrt(Pu/(fc*b*h)))
    Cm=0.6+0.4*m1/m2;
    if Cm<0.4
        Cm=0.4;
    end
    k=0.5;
    Hprima=lelem*k;
    u=0.5;
    Ec=14000*fc^0.5;
    Ig=inertiax;
    EI=0.4*Ec*Ig/(1+u);
    Pc=pi^2*EI/(Hprima^2);

    Fab=Cm/(1-Pu/(0.75*Pc));
    if Fab<1.0
        Fab=1;
    end
    Mcx=Fab*m2;
end

