clear all
clc

cols_sym_asym_isr="Asymmetric";
if cols_sym_asym_isr=="Symmetric"
    pu_cols=[29.19, 29.06, 28.93, 28.93, 28.93, 28.93, 28.93]; % symmetric rebar
elseif cols_sym_asym_isr=="Asymmetric"
    pu_cols=[32.23, 32.10, 31.96, 31.96, 31.96, 31.96, 31.96;
            36.0, 36.0, 36.0, 36.0, 36.0, 36.0, 36.0]; % asymmetric rebar

elseif  cols_sym_asym_isr=="ISR"
    pu_cols=[28.93];
end

height=400; %cm
b=60; % cm
h=60; % cm
fy=4200; % yield stress of rebars 
fc=280; % Kg/cm2
load_conditions=[1 15e3 32e5 8e5]; % [nload, Pu, Mx, My] (Ton-m)
rec=[4 4]; % [coverx covery] (cm)

condition_cracking="Cracked";
ductility=3;

% Slenderness effects ..................................................
delta=0.1; %cm
inertiax=1/12*b*h^3;
inertiay=1/12*h*b^3;
Vu=1000; % Kg

% moments generated by the forces that caused depreciable displacements
% for both axis directions
m2bx=0;
m2by=0;
m2b=[m2bx,m2by];

m1bx=0;
m1by=0;
m1b=[m1bx,m1by];

% moments generated by the forces that caused the greater displacements
% for both axis directions
m2sx=load_conditions(1,3);
m2sy=load_conditions(1,4);
m2s=[m2sx,m2sy];

m1sx=0;
m1sy=0;
m1s=[m2sx,m2sy];

Pu=max(abs(load_conditions(1,2)));
[Mcx,Mcy,load_conditions]=AmpMomSlenderColumns(b,h,fc,Pu,...
                m1b,m1s,m2b,m2s,delta,height,inertiax,inertiay,Vu);
            
load_conditions(1,2)=load_conditions(1,2)*1e-3;
load_conditions(1,3:4)=load_conditions(1,3:4)*1e-5;

optimaPlot=1;
plotResults=1;
% _______________________________________________________________________

[Inertia_xy_modif,b,h,bestArrangement,best_disposicion,cost_elem_col,...
Ac_sec_elem,Ef_sec_col,Mr_col]=isrColumnsSymAsym(pu_cols,height,b,h,rec,...
fy,fc,load_conditions,cols_sym_asym_isr,condition_cracking,ductility,optimaPlot);
